### ISSUE TITLE
Q: How to use this in already `use GenServer` scenario?

### ISSUE THREAD

**Issue by elvanja** [sasa1977/parent#10]
Hi,

This looks very promising for this use case I'm working on: I need to run periodic & scheduled jobs that fetch various data independently from external source and cache it in given node. Caveat is that I can't pre-define data to fetch, or predict refresh interval. Hence the idea to use some way for the client code to define when to go for new data. Enter `Periodic` 😄 

Currently, I have a module that describes the common things such a cache should do and client code can `use` it to build cache `GenServer`s and put them in client supervision tree, where needed.

Here's a breakdown of that idea (a simplification that stores data in memory):
```elixir
defmodule GenCache do
  defmacro __using__(using_opts) do
    quote location: :keep do
      use GenServer

      require Logger

      def start_synchronization(pid) when is_pid(pid) do
        Process.send_after(pid, :synchronize, 1)
        :ok
      end

      def start_link(opts) do
        {:ok, pid} = GenServer.start_link(__MODULE__, :ok, opts)
        start_synchronization(pid)
        {:ok, pid}
      end

      @impl GenServer
      def init(:ok) do
        opts = unquote(using_opts)
        query = Keyword.fetch!(opts, :query)
        client = Keyword.fetch!(opts, :client)

        {:ok, %{
          last_synced_at: nil,
          query: query,
          client: client,
          data: []
        }}
      end

      @impl GenServer
      def handle_info(:synchronize, state) do
        cache_pid = self()

        Task.start(fn ->
          result = state.client.execute(state.query)
          :ok = GenServer.call(cache_pid, {:synchronization_result, result})
        end)

        {:noreply, state}
      end

      @impl GenServer
      def handle_call({:synchronization_result, {:ok, new_data}}, _from, state) do
        new_state = Map.merge(state, %{
          data: new_data,
          last_synced_at: DateTime.utc_now()
        })

        Process.send_after(self(), :synchronize, 5_000)
        {:reply, :ok, new_state}
      end

      @impl GenServer
      def handle_call({:synchronization_result, reason}, _from, state) do
        Logger.warn("Could not fetch data, reason: #{inspect(reason, pretty: true)}")
        Process.send_after(self(), :synchronize, 1_000)
        {:reply, :ok, state}
      end

      defoverridable start_link: 1
    end
  end
end
```

And this is one example of it's usage:
```elixir
defmodule SomeDataCache do
  use GenCache, query: AQueryDefinition, client: ExternalDataClient
end
```

After which `SomeDataCache` can be placed somewhere in the supervision tree.

In this example, fetching data is not really scheduled and it depends on time spent in client request etc. Hence the idea to use something that gives more control. But, I'm at loss to where to put `Periodic`. Ideally it would be part of `GenCache` and it's parameters would be supplied through it. But, just can't figure out how to do that. Any ideas?

Thank you for your time!

**Comment by sasa1977** [comment]
From what I can tell, the specifics of your periodic job are:

1. The interval represents the time between the end of the last success and the start of the next job.
2. On error, the interval is shorter.
3. You manage the state inside the job

Periodic supports 1, but not 2 or 3. You can use the lower abstraction [Parent.GenServer](https://hexdocs.pm/parent/Parent.GenServer.html) to handle those. I'll explain this a bit later, but let's for the moment ignore this deficiency and see how we could use `Periodic`:

```elixir
defmodule GenCache do
  def start_link(opts) do
    Periodic.start_link(
      every: :timer.seconds(5),

      # in shifted mode, the interval represents the time between end of the last job and the
      # start of the next
      delay_mode: :shifted, 

      run: fn -> Keyword.fetch!(opts, :client).execute(Keyword.fetch!(opts, :query)) end,

      # maybe include some other option like `:on_overlap` or `:timeout`.
      # See https://hexdocs.pm/parent/Periodic.html#module-options for details.
    )
  end

  def child_spec(opts) do
    %{
      type: :supervisor,
      start: {__MODULE__, :start_link, [opts]}
    }
  end
end
```

With such module in place you can start the process on demand as `GenCache.start_link(client: some_client, query: some_query)`, or you can start it under some supervisor using the `{GenCache, opts}` child spec.

As I said, Periodic doesn't support varying intervals (i.e. different interval on success/error), nor statefulness. However, if you want to have those, you can reach for `Parent.GenServer`. The code will be very similar to your solution, and in fact it might even require a bit more lines of code. However, it will be more robust. For example in the snippet you provided, you're using `Task.start`. As a result, if the task crashes your periodic job will stop. In addition, if the GenServer is taken down, the child job will still linger on, which leaves you with dangling processes and weird undefined behaviour.

The point of `Parent.GenServer` is to assist with the task of parenting processes. Such task requires a bit of manual bookkeeping, and this is mostly taken care of by `Parent.GenServer` which reduces the chance of potential errors. I advise you to look at the [moduledoc](https://hexdocs.pm/parent/Parent.GenServer.html), and the [rationale doc](https://hexdocs.pm/parent/rationale.html#content). In particular, [this section](https://hexdocs.pm/parent/rationale.html#periodic-job-execution) shows a very simple implementation of a periodic job.

In your case, a basic sketch would look like:

```elixir
defmodule GenCache do
  use Parent.GenServer

  @impl GenServer
  def init(:ok) do
    state = # ...
    start_job(state)
    {:ok, state}
  end

  @impl GenServer
  def handle_info({:result, result}, state) do
    # enqueue the next job, e.g. using Process.send_after
  end

  @impl Parent.GenServer
  def handle_child_terminated(:job, _meta, _pid, reason, state) do
    if reason != :normal, do:
      # the child crashed -> enqueue the next job
  end

  defp start_job(state) do
    me = self()

    Parent.GenServer.start_child(%{
      id: :job,
      start: fn ->
        Task.start_link(fn ->
          result = run_job(state)
          send(me, {:result, result})
        end)
      end
    })
  end
end
```

Let me know if you have further questions.

**Comment by elvanja** [comment]
For the problem at hand, I see that I wasn't clear enough on intention, apologies! You noticed nicely the difference in delay after success or failure, but here's a hopefully better explanation of the idea:
- fetch (new) data at the start of every minute
- in case of success, just keep going per that same schedule
- in case of failure, try and fetch data sooner, e.g. with a short delay or some such
- it doesn't matter if such fetch attempt lands e.g. 10 seconds before next usual run, the next usual run can do it's work
- if fetch is in progress, do not start a new one
- haven't considered fetch timeouts at this time

I guess the periodic nature of fetching data could be solved by finding a nice measure of `:when` and `:every` for `Periodic`. So that leaves the problem of how to make it work.

The `Parent` idea is neat. It is definitely something I need to look into a bit deeper. Especially given the notes about `Task.start` and the problems it carries with it. Much appreciated. Still, it doesn't solve the scheduling problem (or maybe I'm missing something).

After reading this, maybe it makes sense to create a `GenCacheScheduler` module (almost exactly like `GenCache` with `Periodic` from above reply) that would accept related `GenCache` as reference and just invoke `fetch` on it at given intervals. Still need to figure out how to achieve different logic per success/failure.

Anyway, thanks for the tips, definitely food for thought 👍 😄

**Comment by sasa1977** [comment]
You could handle error timeout & retry as a part of the job itself. So something like:

```elixir
Periodic.start_link(
  every: :timer.minutes(1),

  # if the previous instance is still running, don't start the new one
  on_overlap: :ignore,

  run: fn ->
    Stream.repeatedly(fn -> do_something(...) end)
    |> Stream.map(fn result ->
      unless success?(result), do: Process.sleep(1000)
      result
    end)
    |> Enum.find(&success?/1)
    |> do_something_with_success()
  end
)
```

This will not handle the scenario where the job crashes (unhandled exception or crash of a linked process), but you're not handling such scenario in your example anyway :-)

I'll keep your scenario in mind and see if I can add some clean way of supporting different delays for success/failure. But in general I'm somewhat careful about adding too many options to periodic, because it will grow into a monster which will be hard to grasp, both for users and maintainers. 

Any more elaborate scenarios can be implemented with `Parent.GenServer`. It requires more typing and a bit of wheel reinventing, but it is therefore fully flexible.

> The Parent idea is neat. 
> ...
> Still, it doesn't solve the scheduling problem (or maybe I'm missing something).

Whatever you can do with GenServer, you can also do with Parent.GenServer, so you can definitely solve that problem with it. Of course it's not solved for you out of the box, you need to implement that code :-) Parent only helps with management of child processes, nothing more.

**Comment by elvanja** [comment]
Update: WRT scheduling, found a simple way to support scheduling, although without separate handling of success and failure in that module. Boils down to simple periodic module in supervision tree, that just invokes `:synchronize` on related cache module. On error, I can invoke additional refresh/fetch in cache itself. Goes something like this:

```elixir
defmodule CacheForDataX.Scheduler do
  def child_spec(_) do
    Periodic.child_spec(
      id: __MODULE__,
      run: fn -> GenServer.call(CacheForDataX, :synchronize) end,
      every: :timer.seconds(5)
    )
  end
end
```

It works under assumption that cache module is started named, which is OK, since there's no need to keep multiple caches of same data (for the moment that is). A special note here is that I'm building a sort of dynamic supervisor for all the caches in the system. Which requires creating such schedulers during `Supervisor.init`. For that, resorted to `&Code.eval_string/1` to get the schedulers into place. Another downside is that I need to pass periodic related params (e.g. for `:every`) in child definition in supervisor, as opposed from defining it in cache module (where it kind of belongs).

I guess that will do for now. Next step would be to use `Parent` to build all that and avoid the `Task.start` pitfalls. That will take some time though 😄 

Anyway, appreciate the input!

**Comment by sasa1977** [comment]
If you're doing that, you could as well invoke `:timer.send_interval(:timer.seconds(5), :synchronize)` from GenServer's `init/1`. It won't require another process, and you won't need to name your GenServer. See [:timer docs](https://erlang.org/doc/man/timer.html#send_interval-2) for details.

I must admit that something in this architecture you've presented feels off. You keep one GenServer per some distinct piece of data (a key?). I'm not completely sold on this approach and I wonder why not e.g. maintain one ets table for the entire cache, and then have periodic workers which populate this table. But it's unclear from your code what do you actually do with the cache.

**Comment by elvanja** [comment]
For business related reasons, and which can't be changed, the requirement is to execute refreshes per given cron expressions. It's rather limiting, I know, but unfortunately can't be avoided.

As for data that is cached, it's actually "per table". E.g. list of all users might be one of the tables that are fetched from that external data source, list of various rules to what can be done in the system might be another. Some data sets will also be rather large (couple of million of records). Also, some data sets are not flat but can be nested (think document data storage or result of an SQL query with joins). Another problem is that I don't know all the data which will be cached like this upfront. On top of that, the client code needs to subscribe to data changes too.

The idea I'm working on is to provide a mechanism that will be able to handle refreshing, storing, and accessing the cached data and for client code to just supply either description of data it needs to keep (via e.g. struct or maybe Ecto schema - even though it's not DB related), or module that implements the cache and inherits the cache behaviour from one of the base caches. I got this far already, being able to use various flavors of defining data to cache. But, now have to incorporate that cron requirement into the mix.

Data is actually saved in an ETS table, one ETS table per data set. Each cache has it's own ETS table to work with. The memory storage I presented in examples here was just to make the sample code shorter, even though I have base cache modules that supports memory storage too (could be used during e.g. tests).

This is all in rather exploratory stage at the moment, so it's quite likely that I'm not on the right track at all. But hey, fun time for me 😄

BTW, just reading periodic code gives some ideas. E.g. I don't even need all the bells and whistles it can do, because my rules are a bit simpler. So maybe I can just partially copy the idea. And the parent gen server notes are a treasure for sure!

**Comment by sasa1977** [comment]
Judging by my current understanding, it looks like basing your solution on Parent.GenServer is possibly a better fit, because you seem to have a need for a rich behaviour that goes beyond simple execute something every X (which is what Periodic has been designed for). Alternatively, the solution I mentioned in [this comment](https://github.com/sasa1977/parent/issues/10#issuecomment-614802883) might also work, but it's hard for me to provide a strong suggestion without knowing more details about your business problem, but that falls into the consulting territory (which btw is a service I provide 🙂).

I also feel that there are two separate challenges here. We mostly discussed the process/otp aspect of the solution, but you also occasionally mention the design aspect i.e. how to devise an abstraction which can be easily reused for different cache entries. While these two can't be completely separated, I'd focus first on the first aspect alone, by trying to find a simple and reliable way of managing a single kind of cache. Then I'd move on to building a generalized solution (which I'd probably wouldn't based on macros).

But anyway, if you have some Parent/Periodic specific questions, feel free to ask further.

Best of luck!

**Comment by elvanja** [comment]
Yep, definitely gonna research the `Parent.GenServer` path. And I've relayed the note about consulting further up the chain, thanks for the tip!

BTW, found https://github.com/jshmrtn/crontab as a cron parser, with ability to calculate next execution timestamp relative to some point in time (now or whatever one needs). That in combination with `Periodic`'s `:when` option is a simple way of introducing cron like execution. Probably no need to add in `Periodic` itself though.
