### ISSUE TITLE
Should parent parent other parents?

### ISSUE THREAD

**Issue by chasers** [sasa1977/parent#11]
Hey thanks for this! It was perfect for creating a little simple webpage poller.

Question ... should I or can I use this to parent other parents?

I tried that but it seemed to kill the process as start_link would return and it would kill that process or something. 

Basically I just have `run_job` poll a page and if I find what I need it does it's thing, if it doesn't it sends a message to the supervisor to schedule it in a minute. 

I was thinking of having a parent supervisor then supervise other parents where each would be responsible for polling a page, but I couldn't get that to work.

**Comment by sasa1977** [comment]
In theory, parent can be use to parent other parents, though in practice I feel that this should mostly be avoided, and that you'd likely be better off using regular supervisors. 

The description you provided leaves a lot of questions:

1. Do you need to poll multiple pages or one?
2. If multiple, can they be polled simultaneously?
3. Once you successfully poll the page, do you need to re-poll it after some time?
4. If the poll fails, I presume you want to retry after a back-off period?

In any case, the idea of having a supervisor whose children are parent processes seems like a more idiomatic approach than running parents inside parents :-)

**Comment by chasers** [comment]
Got it ... thanks that's the feeling I got.

Yeah we poll multiple pages concurrently. We only need to hit it once if the data is there that we need but sometimes the data is there only after a few minutes from when we start polling. So I look for that data and poll until it's there.

**Comment by sasa1977** [comment]
Based on what you told me, it doesn't even look like you need parent for this. Why not start a one-off task per each page, with each task polling the page until it succeeds, and then stopping?

**Comment by chasers** [comment]
Yeah it was my understanding that you pretty much always want a task supervised, and I figure it would be a good opportunity to use your library to see how you implemented it. And now I'm already storing some state with it and updating a LiveView with job progress!

**Comment by sasa1977** [comment]
You definitely want every process to be supervised :-) When it comes to tasks, you can use [Task.Supervisor](https://hexdocs.pm/elixir/Task.Supervisor.html#content). Parent is more designed for special "rich supervision" cases, where you want things beyond start/stop/restart. I've expanded on this in the [rationale doc](https://github.com/sasa1977/parent/blob/master/RATIONALE.md).

**Comment by chasers** [comment]
Got it ... I appreciate your time. Definitely need to implement more supervision trees for practice :)
