### ISSUE TITLE
migrate from travis-ci.org

### ISSUE THREAD

**Issue by jlgeering** [sasa1977/parent#18]
from https://travis-ci.org/

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on. 

do you need help migrating from travis-ci.org, and if yes, where to? travis-ci.com? GitHub Actions? CircleCI? ...

cheers
JL

**Comment by sasa1977** [comment]
Thanks for asking! I think GH actions would be a good place. It is on my to-do list, but I wasn't able to find any spare time recently. If you're up for it, a PR which converts the Travis config to the GH actions one would be welcome :-)
