### ISSUE TITLE
Handle throw-returns from GenServer callbacks

### ISSUE THREAD

**Issue by michalmuskala** [sasa1977/parent#3]
GenServer has this annoying "feature" that allows `throw`ing a value to return it from a callback. This can be problematic when you have some uncaught throws since the produced error is very confusing. The simplest way to guard against this is to protect all the calls into the handler module with something like:
```elixir
try do
  apply(handler, mod, args)
catch
  :throw, value -> :erlang.raise(:error, {:nocatch, value}, System.stacktrace())
end
```

**Comment by sasa1977** [comment]
You mean [this](https://github.com/erlang/otp/blob/master/lib/stdlib/src/gen_server.erl#L663)? That's messed up :-) Thanks for the tip!

**Comment by sasa1977** [comment]
@michalmuskala I'm not sure I understand what should be done here. Since `Parent.GenServer` is a `GenServer`, any uncatched throw will be handled exactly the same as in `GenServer`. Where do you suggest including this special handling of uncaught thrown values?

**Comment by michalmuskala** [comment]
The problem is that all callbacks in `GenServer` allow you to "return" by throwing. This means that, for example:

```
def handle_call(_req, _from, _state) do
  throw {:reply, :ok, :foobar}
end
```

this code in the callback module, would bypass any logic `Parent` has and return directly to the `GenServer`. This might cause confusing errors in case of uncaught throws.

**Comment by sasa1977** [comment]
The thing is that a GenServer call is immediately delegated to the callback module, and there's no post-processing of the result in `Parent` (see [here](https://github.com/sasa1977/parent/blob/master/lib/parent/gen_server.ex#L252)), so there's no logic to be bypassed.

I should probably still add a test to ensure that "return by throwing" indeed works as expected.

**Comment by michalmuskala** [comment]
Ah, this indeed means there's no issue since the state is stored in the pdict and not in the regular state of the server.

**Comment by sasa1977** [comment]
Yeah, that's an unintended benefit in this case :-) Btw. I briefly explained the reason for using pdict [here](https://github.com/sasa1977/parent/blob/master/RATIONALE.md#state-management).
